brew install git
brew install zsh
brew install htop
brew install z
brew install fzf
brew install bat
brew install exa
brew install fd
brew install ripgrep
brew install peco
brew install tig
brew install thefuck
brew install ncdu
brew install httpie
brew install asciinema
brew install neofetch
brew install cmake
brew install nano
brew install node
brew install openvpn
brew install perl
brew install pstree
brew install tcpdump
brew install util-linux
brew install whois
brew install wireguard-tools
brew install wireshark
# installing powerlevel9k
brew tap sambadevi/powerlevel9k
brew install powerlevel9k
# installing hexyl
curl -L -o hexyl.tar.gz https://github.com/sharkdp/hexyl/releases/download/v0.3.0/hexyl-v0.3.0-x86_64-apple-darwin.tar.gz
tar -xf hexyl.tar.gz
mv hexyl-v0.3.0-x86_64-apple-darwin/hexyl /usr/local/bin
chmod +x /usr/local/bin/hexyl
rm hexyl.tar.gz
rm -rf hexyl-v0.3.0-x86_64-apple-darwin/